<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <groupId>com.sky</groupId>
    <artifactId>take-out</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>take-out</name>

    <modules>
        <module>take-out-common</module>
        <module>take-out-pojo</module>
        <module>take-out-system</module>
        <module>take-out-framework</module>
        <module>take-out-admin</module>
        <module>take-out-pay</module>
        <module>take-out-mock-wechat</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <take-out.version>0.0.1-SNAPSHOT</take-out.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>3.5.17</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.sky</groupId>
                <artifactId>take-out-common</artifactId>
                <version>${take-out.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sky</groupId>
                <artifactId>take-out-pojo</artifactId>
                <version>${take-out.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sky</groupId>
                <artifactId>take-out-system</artifactId>
                <version>${take-out.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sky</groupId>
                <artifactId>take-out-framework</artifactId>
                <version>${take-out.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sky</groupId>
                <artifactId>take-out-pay</artifactId>
                <version>${take-out.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sky</groupId>
                <artifactId>take-out-mock-wechat</artifactId>
                <version>${take-out.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
